import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        Montserrat: "Montserrat",
        Wadik: "Wadik",
        TimesNewRoman: "Times New Roman",
        Lato: "Lato",
        Spartan: "Spartan",
        Calibri: "Calibri",
      },
      colors: {
        white: "#FFFFFF",
        lightCyan: "#E0FFFF",
        cyan50: "#d9f8f8",
        teal: "#008080",
        aquamarine: "#7FFFD4",
        chineseSilver: "#CBCBCB",
        darknavy: "#092236",
        lightnavy: "#042A48",
        cloud: "#d9d9d9",
        cultured: "#F7F6F7",
        smoke: "#C4C4C4",
        orange: "#F7971E",
        alert: "#FF5555",
        success: "#10C623",
        gray: "#929292",
        graphite: "#6F6F6F",
        metal: "#767676",
        grayX11: "#BEBEBE",
        truegray: "#EBEBEB",
        silver: "#DEDEDE",
        light: "#EFEFEF",
        heavy: "#CCCCCC",
        sky: "#627EEA",
        blue: "#0075FF",
        red: "#F00",
        lightGray: "#CED3D7",
        orangePeel: "#FF9D01",
        spanishGray: "#949292",
        chocolate: "#DE7420",
        yellowOrange: "#FBB03B",
        princetonOrnage: "#E5811F",
        denimBlue: "#2243A4",
        fluorescentBlue: "#FB3B3B",
        grayx11: "#BABABA",
        mayGreen: "#3C6B00",
        doveGray: "#636363",
        green: "#0B9B2D",
        sonicSilver: "#7A7A7A",
        platium: "#E8E8E8",
        navyblue: "#134663",
        ickyGreen: "#86B526",
        lightGray2: "#424242",
        deepGray: "#2B2B2B",
        darkGrey: "#373737",
        darkLava: "#493830",
        cola: "#412e25",
        umber: "#65574A",
        monsoon: "#898989",
        maastrichtBlue: "#092136",
        laSalleGreen: "#048332",
        oliveDrab: "#639A0F",
        carminePink: "#F34A4A",
        midGrey: "#5C6369",
        metallicSilver: "#C4C7C9",
        desertStorm: "#F7F7F7",
        greyGoose: "#D2D2D2",
        mercury: "#E9E9E9",
        lavenderMist: "#E2E6E9",
        whiteLilac: "#F6F6F6",
        iron: "#CED4DA",
        spinishgray: "#989898",
        greenHaze: "#0DA06A",
        aquaSpring: "#E9FAEB",
        pumpkinOrange: "#FB7E15",
        oldLace: "#FFF5EB",
        pearl: "#FBF0F0",
        coolGrey: "#A0A3A5",
        blueChalk: "#E7EAEE",
        rockBlue: "#92B5D0",
        davysGrey: "#565656",
        cyanBlue: "#0A7AFF",
        beer: "#F8931F",
        roseMadder: "#DB2E2E",
        lightGrey: "#D9D9D9",
        riverBed: "#3A4E5E",
        granite: "#808080",
      },
      backgroundImage: {},
      backgroundPosition: {
        mainBgPosition: "left -200px",
      },
      borderWidth: {
        1: "1px",
      },
      backgroundSize: {
        full: "100% 100%",
      },
      borderRadius: {
        bg: "30px",
      },
      boxShadow: {
        challengeButton: "0px 12px 8px 0px rgba(0, 0, 0, 0.45)",
        disabledChallengeButton: "0px 4px 8px 0px rgba(0, 0, 0, 0.35)",
        calendarBox: "0px 4px 25px 0px rgba(0, 0, 0, 0.10)",
        dayFilterBox: "0px 2px 2px 0px rgba(0, 0, 0, 0.20)",
        ortherFilterBox: "0px 4px 1px 0px rgba(0, 0, 0, 0.05)",
        mdBlack: "3px 4px 11px 0px rgba(0, 0, 0, 0.23)",
      },
    },
  },
  plugins: [
    require("@headlessui/tailwindcss"),
    require("tailwind-scrollbar")({ nocompatible: true }),
  ],
};

export default config;
